## Data quality analysis

In [11]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import os
import sys

sys.path.append(os.path.abspath('..'))
from src.data_load import load_nuclear_data

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)

In [12]:
df = load_nuclear_data('../data/raw/nuclear_safety.xlsx')
df.head()

,year,quarter,station,irg,irg_index,iodine_ radionuclides,iodine_ radionuclides_index,stable_radionuclides,stable_ radionuclides_index,cs_137_emission,co_60_ emission,cs_137_dump,co_60_dump,volume,index_radioactive_releas,index_dump
0,2018,1,ЗАЕС,89.0,0.13,260.0,0.0,650.0,0.03,1980.0,1020.0,4330.0,3670.0,833000.0,0.149,0.330
1,2018,1,РАЕС,105.0,0.16,147.0,0.0,269.0,0.07,587.0,165.0,4800.0,620.0,2220000.0,0.780,0.096
2,2018,1,ЮУАЕС,45.0,0.10,76.0,0.0,116.0,0.02,136.0,373.0,390.0,370.0,14600.0,0.136,0.284
3,2018,1,ХАЕС,31.0,0.07,26.8,0.0,37.5,0.00,29.4,13.8,380.0,NaN,22070.0,0.110,0.030
4,2018,2,ЗАЕС,84.0,0.12,262.0,0.0,640.0,0.03,453.0,1003.0,4627.0,3432.0,812667.0,0.115,0.910

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   year                         128 non-null    int64
 1   quarter                      128 non-null    int64
 2   station                      128 non-null    object
 3   irg                          115 non-null    float64
 4   irg_index                    115 non-null    float64
 5   iodine_ radionuclides        115 non-null    float64
 6   iodine_ radionuclides_index  115 non-null    float64
 7   stable_radionuclides         115 non-null    float64
 8   stable_ radionuclides_index  115 non-null    float64
 9   cs_137_emission              115 non-null    float64
 10  co_60_ emission              115 non-null    float64
 11  cs_137_dump                  115 non-null    float64
 12  co_60_dump                   98 non-null     float64
 13  volume                       115 non-null    float64
 14  index_radioactive_releas     115 non-null    float64
 15  index_dump                   115 non-null    float64
dtypes: float64(13), int64(2), object(1)
memory usage: 16.1+ KB

In [18]:
print("Shape:", df.shape)

Shape: (128, 16)

In [23]:
df.isna().sum()

year                            0
quarter                         0
station                         0
irg                            13
irg_index                      13
iodine_ radionuclides          13
iodine_ radionuclides_index    13
stable_radionuclides           13
stable_ radionuclides_index    13
cs_137_emission                13
co_60_ emission                13
cs_137_dump                    13
co_60_dump                     30
volume                         13
index_radioactive_releas       13
index_dump                     13
dtype: int64

In [25]:
missing = df.isna().mean().sort_values(ascending=False)
missing_df = pd.DataFrame({
    "missing_ratio": missing
})

display(missing_df.head(20))

                             missing_ratio
co_60_dump                        0.234375
irg                               0.101562
iodine_ radionuclides             0.101562
iodine_ radionuclides_index       0.101562
stable_radionuclides              0.101562
co_60_ emission                   0.101562
stable_ radionuclides_index       0.101562
irg_index                         0.101562
cs_137_dump                       0.101562
volume                            0.101562
index_radioactive_releas          0.101562
cs_137_emission                   0.101562
index_dump                        0.101562
quarter                           0.000000
station                           0.000000
year                              0.000000

In [39]:
df.drop(['year','quarter'], axis=1).describe()

,irg,irg_index,iodine_ radionuclides,iodine_ radionuclides_index,stable_radionuclides,stable_ radionuclides_index,cs_137_emission,co_60_ emission,cs_137_dump,co_60_dump,volume,index_radioactive_releas,index_dump
count,115.000000,115.000000,115.000000,115.0,115.000000,115.00000,115.000000,115.000000,115.000000,98.000000,1.150000e+02,115.000000,115.000000
mean,67.106957,0.118261,85.119130,0.0,238.275652,0.03087,237.293913,320.064348,3973.660870,1300.782755,1.025583e+06,1.044730,0.766174
std,41.597420,0.059150,85.677601,0.0,199.293961,0.02674,356.340647,438.618397,4778.517156,1681.422302,1.377303e+06,1.339668,0.887026
min,21.000000,0.050000,15.000000,0.0,27.600000,0.00000,11.200000,12.000000,67.000000,2.210000,1.480000e+03,0.070000,0.000000
25%,31.000000,0.070000,32.000000,0.0,39.000000,0.00000,33.000000,50.000000,578.000000,219.000000,2.223500e+04,0.200000,0.127500
50%,50.000000,0.100000,64.000000,0.0,219.000000,0.03000,89.000000,201.000000,2109.000000,668.000000,6.584000e+04,0.600000,0.380000
75%,97.500000,0.150000,84.500000,0.0,296.500000,0.06000,296.500000,412.500000,5220.500000,1522.750000,2.627025e+06,0.915000,1.125500
max,205.000000,0.340000,552.000000,0.0,754.000000,0.09000,2115.000000,3639.000000,20248.000000,9000.000000,4.469170e+06,4.967000,4.209000

In [28]:
dup_rows = df.duplicated().sum()
print("Duplicate full rows:", dup_rows)

Duplicate full rows: 0

In [32]:
df.head()

,year,quarter,station,irg,irg_index,iodine_ radionuclides,iodine_ radionuclides_index,stable_radionuclides,stable_ radionuclides_index,cs_137_emission,co_60_ emission,cs_137_dump,co_60_dump,volume,index_radioactive_releas,index_dump
0,2018,1,ЗАЕС,89.0,0.13,260.0,0.0,650.0,0.03,1980.0,1020.0,4330.0,3670.0,833000.0,0.149,0.330
1,2018,1,РАЕС,105.0,0.16,147.0,0.0,269.0,0.07,587.0,165.0,4800.0,620.0,2220000.0,0.780,0.096
2,2018,1,ЮУАЕС,45.0,0.10,76.0,0.0,116.0,0.02,136.0,373.0,390.0,370.0,14600.0,0.136,0.284
3,2018,1,ХАЕС,31.0,0.07,26.8,0.0,37.5,0.00,29.4,13.8,380.0,NaN,22070.0,0.110,0.030
4,2018,2,ЗАЕС,84.0,0.12,262.0,0.0,640.0,0.03,453.0,1003.0,4627.0,3432.0,812667.0,0.115,0.910

In [36]:
stations = df['station'].unique()
print(f"Кількість унікальних станцій: {len(stations)}")
print(f"Список станцій: {stations}")

Кількість унікальних станцій: 5
Список станцій: ['ЗАЕС' 'РАЕС' 'ЮУАЕС' 'ХАЕС' 'ПАЕС']

Оскільки в даних є "ЮУАЕС" та "ПАЕС" (це одна і та сама Південноукраїнська АЕС, яку перейменували), необхідно їх об'єднати в одну ПАЕС. Це допоможе уникнути помилок, коли при аналізі показників для кожної із станції.

In [38]:
df['station'] = df['station'].replace('ЮУАЕС', 'ПАЕС')
print(f"Список станцій: {df['station'].unique()}")

Список станцій: ['ЗАЕС' 'РАЕС' 'ПАЕС' 'ХАЕС']

In [44]:
rows_with_nan = df[df.isnull().any(axis=1)]
display(rows_with_nan)

,year,quarter,station,irg,irg_index,iodine_ radionuclides,iodine_ radionuclides_index,stable_radionuclides,stable_ radionuclides_index,cs_137_emission,co_60_ emission,cs_137_dump,co_60_dump,volume,index_radioactive_releas,index_dump
3,2018,1,ХАЕС,31.0,0.07,26.8,0.0,37.5,0.0,29.4,13.8,380.0,NaN,22070.0,0.11,0.030
7,2018,2,ХАЕС,30.0,0.07,27.6,0.0,27.6,0.0,21.1,12.2,1380.0,NaN,42484.0,0.23,0.110
11,2018,3,ХАЕС,33.0,0.07,30.0,0.0,30.0,0.0,24.0,13.0,700.0,NaN,20000.0,0.11,0.130
15,2018,4,ХАЕС,38.0,0.08,33.0,0.0,40.0,0.0,101.0,103.0,1573.0,NaN,46160.0,0.13,0.146
19,2019,1,ХАЕС,38.3,0.08,33.3,0.0,34.4,0.0,11.2,24.4,263.0,NaN,12800.0,0.13,0.000
23,2019,2,ХАЕС,40.0,0.09,35.0,0.0,35.2,0.0,25.1,14.0,1390.0,NaN,69120.0,0.12,0.103
27,2019,3,ХАЕС,35.0,0.08,32.0,0.0,33.0,0.0,22.0,64.0,547.0,NaN,15000.0,0.15,0.113
31,2019,4,ХАЕС,35.0,0.07,33.0,0.0,39.0,0.0,16.0,102.0,5700.0,NaN,93100.0,0.12,0.214
35,2020,1,ХАЕС,31.0,0.07,31.0,0.0,31.0,0.0,18.0,15.0,148.0,NaN,11440.0,0.12,0.010
39,2020,2,ХАЕС,31.0,0.07,36.0,0.0,37.0,0.0,19.0,171.0,319.0,NaN,22000.0,0.17,0.030
43,2020,3,ХАЕС,32.0,0.07,34.0,0.0,33.0,0.0,19.0,18.0,783.0,NaN,36620.0,0.13,0.080
47,2020,4,ХАЕС,32.0,0.07,32.0,0.0,39.0,0.0,16.0,196.0,1790.0,NaN,72000.0,0.13,0.125
51,2021,1,ХАЕС,31.0,0.07,31.0,0.0,31.0,0.0,19.0,12.0,947.0,NaN,27750.0,0.13,0.040
55,2021,2,ХАЕС,40.0,0.09,83.0,0.0,39.0,0.0,22.0,16.0,687.0,NaN,44008.0,0.18,0.070
59,2021,3,ХАЕС,36.0,0.08,39.0,0.0,35.0,0.0,20.0,14.0,587.0,NaN,30808.0,0.17,0.110
63,2021,4,ХАЕС,28.0,0.06,28.0,0.0,28.0,0.0,22.0,15.0,587.0,NaN,26530.0,0.14,0.140
67,2022,1,ХАЕС,31.0,0.07,84.0,0.0,32.0,0.0,35.0,23.0,540.0,NaN,23812.0,0.11,0.030
76,2022,4,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,2023,1,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,2023,2,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2023,3,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,2023,4,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2024,1,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,2024,2,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,2024,3,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,2024,4,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,2025,1,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,2025,2,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,2025,3,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,2025,4,ЗАЕС,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Аналіз пропущених значень виявив два ключові аспекти. По-перше, з 2022 року повністю відсутні дані щодо Запорізької АЕС, що пов’язано з воєнними діями. По-друге, для Хмельницької АЕС відсутні дані за показником co_60_dump (скиди Кобальту-60). Це може свідчити про специфіку моніторингу або про незафіксовані нульові значення. 
Ці особливості необхідно враховувати під час подальшого аналізу та візуалізації результатів. Видалення таких записів є недоцільним через невеликий обсяг даних. Проте заповнення пропусків середніми значеннями також не є коректним для даних екологічного та радіологічного характеру, оскільки це може спотворити реальну картину показників.